### ISSUE TITLE
Upload precompiled versions to Releases rather than including them in the repository

### ISSUE THREAD

**Issue by qwertychouskie** [TheCod3rYouTube/PS5NorModifier#6]
Uploading pre-compiled binary files/archives directly to the Git repository is generally a bad idea.  GitHub lets you define Releases, and those Releases can have files attached to them.  This is the generally recommended way to do things.  It can even be set up where when you create a Release tag, the code is automatically compiled and the resulting program attached to the Release.

**Comment by TheCod3rYouTube** [comment]
Thanks bud, done that with this release :)
